UPDATE HH_USERAPP
  SET 
      US_NOME = @US_NOME, 
      US_COGNOME = @US_COGNOME, 
      US_USERNAME = @US_USERNAME, 
      US_PASSWORD = @US_PASSWORD, 
      US_CODAGE = @US_CODAGE, 
      US_SUPERAGENTE = @US_SUPERAGENTE, 
      US_ABILITATO = @US_ABILITATO,
	  US_EMAIL =@US_EMAIL

WHERE US_ID = @US_ID;