/****** Script per comando SelectTopNRows da SSMS  ******/
SELECT [mese]
      ,[mm_quant]
      ,[tm_anno]
      ,[an_conto]
      ,[an_descr1]
      ,[an_prov]
      ,[ar_codart]
      ,[ar_descr]
      ,[ar_gruppo]
      ,[tb_desgmer]
      ,[ar_sotgru]
      ,[tb_dessgme]
      ,[ar_famprod]
      ,[tb_descfam]
      ,[ar_codmarc]
      ,[tb_desmarc]
      ,[mm_codagen]
      ,[tb_descage]
      ,[mm_stasino]
      ,[mm_prezzo]
      ,[mm_scont1]
      ,[mm_scont2]
	  ,[mm_scont3]
      ,[mm_valore]
  FROM [LG_STATGEN] where tm_anno = @anno and mese >= @mese and mese <= @mesefine