//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.42000
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DodoPet {
    using System;
    
    
    /// <summary>
    ///   Classe di risorse fortemente tipizzata per la ricerca di stringhe localizzate e così via.
    /// </summary>
    // Questa classe è stata generata automaticamente dalla classe StronglyTypedResourceBuilder.
    // tramite uno strumento quale ResGen o Visual Studio.
    // Per aggiungere o rimuovere un membro, modificare il file con estensione ResX ed eseguire nuovamente ResGen
    // con l'opzione /str oppure ricompilare il progetto VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Query {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Query() {
        }
        
        /// <summary>
        ///   Restituisce l'istanza di ResourceManager nella cache utilizzata da questa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DodoPet.Query", typeof(Query).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Esegue l'override della proprietà CurrentUICulture del thread corrente per tutte le
        ///   ricerche di risorse eseguite utilizzando questa classe di risorse fortemente tipizzata.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a delete from  hhTEMPARTICO.
        /// </summary>
        internal static string ELIMINATEM {
            get {
                return ResourceManager.GetString("ELIMINATEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a SELECT ISNULL(ar_codart, &apos;&apos;) ar_codart, 
        ///       xx_codart, 
        ///       xx_prezzo, 
        ///       ar_descr, 
        ///       ISNULL(
        ///(
        ///    SELECT lc_prezzo
        ///    FROM listini
        ///    WHERE lc_listino = 91 and lc_codart = ar_codart
        ///          AND lc_datscad &gt; GETDATE() and lc_unmis = (select ar_unmis from artico where ar_codart = lc_codart)
        ///), 0) xx_prezzoattuale
        ///FROM hhLISTINODODOPET
        ///     LEFT JOIN artico ON ar_codart = xx_codart;.
        /// </summary>
        internal static string LISTALISTINITEMP {
            get {
                return ResourceManager.GetString("LISTALISTINITEMP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a SELECT concat(tm_numdoc, &apos;~&apos;, tm_serie, &apos;~&apos;, tm_anno, &apos;~&apos;, tm_tipork) xx_chiaveglobale,  
        ///       mm_codart, 
        ///       mm_descr, 
        ///       mm_quant, 
        ///       mm_prezzo, 
        ///       mm_valore, 
        ///       mm_scont1, 
        ///       mm_scont2
        ///FROM movmag m
        ///     INNER JOIN testmag ON tm_serie = m.mm_serie
        ///                           AND tm_anno = m.mm_anno
        ///                           AND tm_tipork = m.mm_tipork
        ///                           AND tm_numdoc = m.mm_numdoc
        ///     INNER JOIN anagra ON an_conto = tm_conto
        ///WHERE mm_ [stringa troncata]&quot;;.
        /// </summary>
        internal static string RigheVenduto {
            get {
                return ResourceManager.GetString("RigheVenduto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a delete from hhLISTINODODOPET.
        /// </summary>
        internal static string SVUOTATEMP {
            get {
                return ResourceManager.GetString("SVUOTATEMP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a SELECT concat(tm_numdoc, &apos;~&apos;, tm_serie, &apos;~&apos;, tm_anno, &apos;~&apos;, tm_tipork) xx_chiaveglobale, 
        ///       tm_datdoc, 
        ///       tm_numdoc, 
        ///       tm_anno, 
        ///       tm_conto, 
        ///       an_descr1, 
        ///	   tm_totdoc
        ///FROM testmag t
        ///     INNER JOIN anagra ON an_conto = tm_conto
        ///     LEFT JOIN destdiv ON tm_coddest = dd_coddest
        ///                          AND tm_conto = dd_conto
        ///WHERE   t.tm_datdoc &gt;= convert(date,@DATAINIZIO) AND  t.tm_datdoc &lt;convert(date,@DATAFINE) AND tm_tipork =&apos;C&apos;
        ///.
        /// </summary>
        internal static string TestateVenduto {
            get {
                return ResourceManager.GetString("TestateVenduto", resourceCulture);
            }
        }
    }
}
